### ISSUE TITLE
[website] Broken Link

### ISSUE THREAD

**Issue by atarax665** [cncf/radar#40]
**ISSUE**:
While going through https://radar.cncf.io/ I found that under ```The Radar Team``` section the link to ```Rajarajan Pudupatti SJ, Vice President of Cloud Platform Delivery at Fidelity Investments``` linkedin profile is broken. 

This is the broken [URL](https://www.linkedin.com/in/rajarajan-pudupatti-sundari-j) that one is being redirected to right now. Update it with the correct URL, that is https://www.linkedin.com/in/rajarajan-pudupatti-sundari-j-64954016b

**Comment by kitarp29** [comment]
Hi @caniszczyk @cjyabraham 
I would love to work on this Issue.
Please assign it to me
