### ISSUE TITLE
Update designs

### ISSUE THREAD

**Issue by cjyabraham** [cncf/radar#48]
We now have approval on [the logos shown here](https://docs.google.com/presentation/d/1krW0cLXR7AEgii8Xi3cKfZgNZ7MzyPQBdbjVtj-lBfg/edit#slide=id.ge40fd7f85c_0_1) and [navbar colors shown here](https://docs.google.com/presentation/d/1krW0cLXR7AEgii8Xi3cKfZgNZ7MzyPQBdbjVtj-lBfg/edit#slide=id.ge38d44da2e_0_0).  To that end, could you change your navbar to #231F20 and swap in [this logo](https://drive.google.com/file/d/15sBM9sF9I19PDZaoEEf6h97AMW8FzMvT/view?usp=sharing)?

**Comment by jordinl83** [comment]
@cjyabraham Please review updated header https://deploy-preview-53--cncf-radar.netlify.app/

I've also changed the color of the footer to black

**Comment by cjyabraham** [comment]
Looks good.  Can you make the logo larger, maybe 230px wide, so it's about as prominent as the logo on https://www.cncf.io/ ?

**Comment by jordinl83** [comment]
@cjyabraham made logo bigger. Please check again

**Comment by cjyabraham** [comment]
LGTM!  Thanks.
